### ISSUE TITLE
Error in fos populate

### ISSUE THREAD

**Issue by cesar-sebastian** [Codevate/restaurant-search-example#2]
When run:
`php app/console fos:elastic:populate`

Return:
`
Resetting app                                                                                        
[Elastica\Exception\ResponseException]                                                
Mapping definition for [name_suggest] has unsupported parameters:  [payloads : true]
`

**Comment by lushc** [comment]
Hi @CesarCarrazana, this should be fixed now, the blog was written when Elasticsearch 2.4 was the latest version so 5.x introduced a few breaking changes.
